import type { CandidateIdentity, ResumeProfile } from '../../shared/types'

export function createStarterResume(identity: CandidateIdentity): string {
  const name = latexEscape(identity.fullName || 'Your Name')
  const contact = [
    identity.email && `\\href{mailto:${latexEscape(identity.email)}}{${latexEscape(identity.email)}}`,
    identity.phone && latexEscape(identity.phone),
    identity.portfolio && link(identity.portfolio),
    identity.github && link(identity.github),
    identity.linkedin && link(identity.linkedin)
  ].filter(Boolean).join(' $|$ ')

  return `% Resume template generated by Internship OS
\\documentclass[letterpaper,11pt]{article}
\\usepackage[empty]{fullpage}
\\usepackage[hidelinks]{hyperref}
\\usepackage{enumitem}
\\usepackage{titlesec}
\\input{glyphtounicode}
\\pdfgentounicode=1
\\pagestyle{empty}
\\setlength{\\parindent}{0pt}
\\titleformat{\\section}{\\large\\bfseries}{}{0em}{}[\\titlerule]

\\begin{document}
\\begin{center}
  {\\Huge\\textbf{${name}}} \\\\
  ${contact || 'email@example.com $|$ github.com/username $|$ linkedin.com/in/username'}
\\end{center}

\\section{Education}
\\textbf{University Name} \\hfill City, State \\
Degree and Major \\hfill Expected Graduation

\\section{Experience}
\\textbf{Role} \\hfill Month Year -- Month Year \\
\\textit{Organization} \\hfill City, State
\\begin{itemize}[leftmargin=*, nosep]
  \\item Replace this text with a verified accomplishment.
  \\item Keep every claim factual, specific, and concise.
\\end{itemize}

\\section{Projects}
\\textbf{Project Name} $|$ Technologies \\hfill Month Year -- Month Year
\\begin{itemize}[leftmargin=*, nosep]
  \\item Describe what you built, how it works, and the verified result.
\\end{itemize}

\\section{Technical Skills}
\\textbf{Languages:} Add verified languages here \\
\\textbf{Tools:} Add verified tools here
\\end{document}
`
}

export function createCandidateProfile(identity: CandidateIdentity, profiles: ResumeProfile[]): string {
  return `# ${identity.fullName || 'Candidate'} — Durable Candidate Profile

This local file stores verified candidate facts shared across Internship OS assistant chats. Add only facts explicitly supplied by the user or already present in a verified resume.

## Goal and constraints

- Primary workflow: manage internship applications and tailored resumes.
- Never invent experience, metrics, dates, skills, credentials, employers, projects, or claims.
- Keep promoted resumes readable and exactly one page.

## Identity and links

- Name: ${identity.fullName}
- Portfolio: ${identity.portfolio}
- GitHub: ${identity.github}
- LinkedIn: ${identity.linkedin}
- Email: ${identity.email}
- Phone: ${identity.phone}

## Resume profiles

${profiles.map((profile) => `- ${profile.name}: ${profile.focus}`).join('\n')}

## Verified candidate facts

- Add verified education, experience, project, skill, preference, and constraint facts here.
`
}

function link(value: string): string {
  const escaped = latexEscape(value)
  const href = /^https?:\/\//i.test(value) ? value : `https://${value}`
  return `\\href{${latexEscape(href)}}{${escaped.replace(/^https?:\/\//i, '')}}`
}

function latexEscape(value: string): string {
  return value.replace(/([#$%&_{}])/g, '\\$1')
}
