import type { CandidateIdentity, ResumeProfile } from '../../shared/types'

export const CANDIDATE_BANK_GUIDANCE_START = '<!-- internship-os:candidate-experience-bank:start -->'
export const CANDIDATE_BANK_GUIDANCE_END = '<!-- internship-os:candidate-experience-bank:end -->'

const CANDIDATE_BANK_INTRO = 'This local file is the active experience bank shared across Internship OS assistant chats. It is working memory, not a frozen biography or a chronological log.'

const CANDIDATE_BANK_GUIDANCE = `${CANDIDATE_BANK_GUIDANCE_START}
## How this experience bank works

- The user's newest statement is authoritative. A correction replaces conflicting details in the named role, project, skill, or preference instead of being appended as another version.
- When an existing entry already contains directly conflicting versions, do not blend them. Prefer a clear later or more-specific correction and consolidate the entry before using it; ask only when the current version cannot be determined and the difference materially affects the task.
- If the user asks to remove, delete, or forget something here, remove it from the active bank. Do not recover it from earlier chats, old drafts, backups, inactive resume profiles, or other historical material unless the user explicitly reintroduces it.
- Use the current request and this active bank for personalized recommendations. The bank is not a limit on new material the user supplies, but items absent from it should not be repeatedly mined from old history.
- Presence in the bank makes an item available, not mandatory. Rank possible material by the current request, target role, relevance, recency, and the user's stated preferences; use only the smallest strong set. Do not keep defaulting to the same older or more detailed project.
- If the user rejects or deprioritizes a suggestion for the current goal, do not offer it again for that goal unless the user asks to reconsider it.
- Add clear, reusable candidate details when the user supplies or accepts them: responsibilities, accomplishments, technologies, projects, education, skills, interests, targets, constraints, and writing preferences. Reusable hypothetical or test material may also be stored when the user asks.
- Consolidate new details into the relevant entry. Avoid duplicate bullets, contradictory variants, and a stream of dated conversation notes.
- Do not persist casual brainstorming, unaccepted assistant suggestions, job-description facts, transient wording, or uncertain guesses. If a detail is useful only for the current task, use it without adding it here.
${CANDIDATE_BANK_GUIDANCE_END}`

export function createStarterResume(identity: CandidateIdentity): string {
  const name = latexEscape(identity.fullName || 'Your Name')
  const contact = [
    identity.email && `\\href{mailto:${latexEscape(identity.email)}}{${latexEscape(identity.email)}}`,
    identity.phone && latexEscape(identity.phone),
    identity.portfolio && link(identity.portfolio),
    identity.github && link(identity.github),
    identity.linkedin && link(identity.linkedin)
  ].filter(Boolean).join(' $|$ ')

  return `% Resume template generated by Internship OS
\\documentclass[letterpaper,11pt]{article}
\\usepackage[empty]{fullpage}
\\usepackage[hidelinks]{hyperref}
\\usepackage{enumitem}
\\usepackage{titlesec}
\\input{glyphtounicode}
\\pdfgentounicode=1
\\pagestyle{empty}
\\setlength{\\parindent}{0pt}
\\titleformat{\\section}{\\large\\bfseries}{}{0em}{}[\\titlerule]

\\begin{document}
\\begin{center}
  {\\Huge\\textbf{${name}}} \\\\
  ${contact || 'email@example.com $|$ github.com/username $|$ linkedin.com/in/username'}
\\end{center}

\\section{Education}
\\textbf{University Name} \\hfill City, State \\
Degree and Major \\hfill Expected Graduation

\\section{Experience}
\\textbf{Role} \\hfill Month Year -- Month Year \\
\\textit{Organization} \\hfill City, State
\\begin{itemize}[leftmargin=*, nosep]
  \\item Replace this text with a compelling accomplishment.
  \\item Keep every claim specific and concise.
\\end{itemize}

\\section{Projects}
\\textbf{Project Name} $|$ Technologies \\hfill Month Year -- Month Year
\\begin{itemize}[leftmargin=*, nosep]
  \\item Describe what you built, how it works, and the result.
\\end{itemize}

\\section{Technical Skills}
\\textbf{Languages:} Add languages here \\
\\textbf{Tools:} Add tools here
\\end{document}
`
}

export function createCandidateProfile(identity: CandidateIdentity, profiles: ResumeProfile[]): string {
  return `# ${identity.fullName || 'Candidate'} — Candidate Experience Bank

${CANDIDATE_BANK_INTRO}

${CANDIDATE_BANK_GUIDANCE}

## Goal and constraints

- Primary workflow: manage internship applications and tailored resumes.
- Keep promoted resumes readable. Page length follows the user's preference.

## Identity and links

- Name: ${identity.fullName}
- Portfolio: ${identity.portfolio}
- GitHub: ${identity.github}
- LinkedIn: ${identity.linkedin}
- Email: ${identity.email}
- Phone: ${identity.phone}

## Resume profiles

${profiles.map((profile) => `- ${profile.name}: ${profile.focus}`).join('\n')}

## Experience bank

### Education

- Add reusable education details here.

### Work experience

- Add roles, responsibilities, accomplishments, outcomes, and technologies here.

### Projects and leadership

- Add active projects, leadership, research, and extracurricular experience here.

### Skills and technologies

- Add skills the candidate wants available for recommendations here.

## Application and writing preferences

- Add durable role targets, content preferences, exclusions, and constraints here.
`
}

export function updateCandidateProfile(source: string, identity: CandidateIdentity, profiles: ResumeProfile[]): string {
  const managedGuidancePattern = new RegExp(
    `${escapeRegExp(CANDIDATE_BANK_GUIDANCE_START)}[\\s\\S]*?${escapeRegExp(CANDIDATE_BANK_GUIDANCE_END)}\\s*`,
    'g'
  )
  let updated = source.replace(managedGuidancePattern, '').trim()
  const title = `# ${identity.fullName || 'Candidate'} — Candidate Experience Bank`
  if (/^#\s+.+$/m.test(updated)) updated = updated.replace(/^#\s+.+$/m, title)
  else updated = `${title}\n\n${updated}`

  const firstSection = updated.search(/^##\s+/m)
  const body = firstSection >= 0 ? updated.slice(firstSection).trim() : ''
  updated = `${title}\n\n${CANDIDATE_BANK_INTRO}\n\n${CANDIDATE_BANK_GUIDANCE}${body ? `\n\n${body}` : ''}`

  const identityBlock = `## Identity and links

- Name: ${identity.fullName}
- Portfolio: ${identity.portfolio}
- GitHub: ${identity.github}
- LinkedIn: ${identity.linkedin}
- Email: ${identity.email}
- Phone: ${identity.phone}
`
  const profileBlock = `## Resume profiles

${profiles.map((profile) => `- ${profile.name}: ${profile.focus}`).join('\n')}
`
  const identityPattern = /^## Identity and links[^\n]*\n[\s\S]*?(?=^##\s|(?![\s\S]))/m
  const profilesPattern = /^## Resume profiles[^\n]*\n[\s\S]*?(?=^##\s|(?![\s\S]))/m

  if (identityPattern.test(updated)) {
    updated = updated.replace(identityPattern, () => `${identityBlock}\n`)
  } else {
    updated = `${updated.trim()}\n\n${identityBlock}`
  }
  if (profilesPattern.test(updated)) {
    updated = updated.replace(profilesPattern, () => `${profileBlock}\n`)
  } else {
    const nextSection = updated.indexOf('\n## ', updated.indexOf('## Identity and links') + 3)
    updated = nextSection >= 0
      ? `${updated.slice(0, nextSection).trim()}\n\n${profileBlock}\n${updated.slice(nextSection + 1).trimStart()}`
      : `${updated.trim()}\n\n${profileBlock}`
  }
  return `${updated.trim()}\n`
}

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
}

function link(value: string): string {
  const escaped = latexEscape(value)
  const href = /^https?:\/\//i.test(value) ? value : `https://${value}`
  return `\\href{${latexEscape(href)}}{${escaped.replace(/^https?:\/\//i, '')}}`
}

function latexEscape(value: string): string {
  return value.replace(/([#$%&_{}])/g, '\\$1')
}
